/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function testConnection(uri: string): Promise<string>
export declare class PlainTextAuthProvider {
  id: number
  static new(): PlainTextAuthProvider
  test(): number
}
export declare class QueryResultWrapper {
  getRows(): Array<RowWrapper>
}
export declare class RowWrapper {
  getColumns(): Array<CqlValueWrapper>
}
export declare class CqlValueWrapper {
  stringify(): string
}
export declare class SessionOptions {
  connectPoints: Array<string>
  static empty(): SessionOptions
}
export declare class SessionWrapper {
  static createSession(options: SessionOptions): Promise<SessionWrapper>
  queryUnpagedNoValues(query: string): Promise<QueryResultWrapper>
}
