/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function testConnection(uri: string): Promise<string>
export declare class PlainTextAuthProvider {
  id: number
  static new(): PlainTextAuthProvider
  static test(): number
}
