# FILE 1 of 2. 
# Docker compose for two machine setup. 

services:
  scylla1:
    image: scylladb/scylla
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9100:9100
      - 19042:19042
      - 19142:19142
    # REMEMBER TO CHANGE THE IP ADDRESS FOR EXTERNAL IP ADDRESS
    # Recommended 1/4 of total RAM
    command: |
      --rpc-address 0.0.0.0
      --listen-address 0.0.0.0
      --seeds 0.0.0.0
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 2
      --memory 1G 
    healthcheck:
      test: [ "CMD", "cqlsh", "scylla1", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 60
