version: "3.7"

networks:
  public:
    name: scylla-one-node-one-shard-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.47.0.0/16
services:
  scylla1:
    image: scylladb/scylla
    networks:
      public:
        ipv4_address: 172.47.0.2
    # Recommended memory: 1/4 of total RAM 
    command: |
      --rpc-address 172.47.0.2
      --listen-address 172.47.0.2
      --seeds 172.47.0.2
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 1
      --memory 1G 
    healthcheck:
      test: [ "CMD", "cqlsh", "scylla1", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 60
