version: "3.7"

networks:
  public:
    name: scylla-three-node-two-shards-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.45.0.0/16
services:
  scylla1:
    image: scylladb/scylla
    networks:
      public:
        ipv4_address: 172.45.0.2
    # REMEMBER TO CHANGE THOSE VALUES FOR ALL INSTANCES
    # Recommended memory: 1/12 [1/(4*numberOfNodes)] of total RAM
    command: |
      --rpc-address 172.45.0.2
      --listen-address 172.45.0.2
      --seeds 172.45.0.2
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 2
      --memory 1G 
    healthcheck:
      test: [ "CMD", "cqlsh", "scylla1", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 60
  scylla2:
    image: scylladb/scylla
    networks:
      public:
        ipv4_address: 172.45.0.3
    command: |
      --rpc-address 172.45.0.3
      --listen-address 172.45.0.3
      --seeds 172.45.0.2
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 2
      --memory 1G
    healthcheck:
      test: [ "CMD", "cqlsh", "scylla2", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      scylla1:
        condition: service_healthy
  scylla3:
    image: scylladb/scylla
    networks:
      public:
        ipv4_address: 172.45.0.4
    command: |
      --rpc-address 172.45.0.4
      --listen-address 172.45.0.4
      --seeds 172.45.0.2,172.45.0.3
      --skip-wait-for-gossip-to-settle 0
      --ring-delay-ms 0
      --smp 2
      --memory 1G
    healthcheck:
      test: [ "CMD", "cqlsh", "scylla3", "-e", "select * from system.local" ]
      interval: 5s
      timeout: 5s
      retries: 60
    depends_on:
      scylla2:
        condition: service_healthy
