name: Run benchmarks
env:
  DEBUG: napi:*
  APP_NAME: scylladb-javascript-driver
  PEDANTIC: true
on:
    workflow_dispatch:
        
jobs:
  build-and-run-benchmarks:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: npm run build -- --target x86_64-unknown-linux-gnu
        node: [ 20 ]
    name: Build and run benchmarks - benchmarks-only - node@${{ matrix.node }}
    runs-on: benchmarks-only
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Breakpoint if tests failed
      #   if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 90m
          authorized-users: adespawn
