name: Check code quality
env:
  DEBUG: napi:*
  APP_NAME: scylladb-javascript-driver
"on":
  push:
    branches:
      - "**"
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Update rust toolchain
        run: rustup update
      - name: Print rustc version
        run: rustc --version
      - name: Print rustfmt version
        run: cargo fmt --version
      - name: Print clippy version
        run: cargo clippy --version
      - name: Install dependencies
        run: npm i
      - name: Cargo fmt
        run: cargo fmt --check
      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Prettier for JS
        run: npx prettier "{lib,examples,test}/**/*.js" --check
      - name: Eslint
        run: npm run eslint      
