name: Run Typescript tests
env:
  DEBUG: napi:*
"on":
  push:
    branches:
      - "**"
jobs:
  build-and-run-tests:
    strategy:
      fail-fast: false
    name: Build and run typescript tests - node@20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.napi-rs
            .cargo-cache
            target/
          key: x86_64-unknown-linux-gnu-cargo-ubuntu-latest
      - name: Install dependencies
        run: npm i
      - name: Run build
        run: npm run build
      - name: Install TypeScript 4.9
        run: npm install -g typescript@4.9
      - name: Compile TypeScript
        run: |
          pushd test/typescript/
          tsc -p .
          node -e "require('./api-generation-test').generate()" > generated.ts
          tsc generated.ts
        shell: bash
